name: CI Pipeline for PR
  
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  check-changes:
    uses: ./.github/workflows/check-changes.yml
    secrets: inherit
  build-test:
    needs: [check-changes]
    if: ${{ needs.check-changes.outputs.src_changed }}  == 'true'
    uses: ./.github/workflows/build-java.yml
    secrets: inherit
  terraform-plan:
    needs: [check-changes]
    if: ${{ needs.check-changes.outputs.infra_changed }}  == 'true'
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
  opa-validation:
    needs: [terraform-plan]
    uses: ./.github/workflows/opa-validation.yml
    secrets: inherit
  code-review:
    uses: ./.github/workflows/code-review.yml
    secrets: inherit
  auto-approve-merge:
    needs: [build-test, terraform-plan, opa-validation, code-review]
    uses: ./.github/workflows/auto-approve-merge.yml
    with:
      is_validated: ${{ needs.opa-validation.outputs.is_validated }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit
